
# POST http://localhost:3001/user/register  HTTP/1.1
# content-type: application/json

# {
#    "username":"laotie",
#    "password":"12345",
#    "email":"163.com"
# }



POST http://localhost:3001/user/login  HTTP/1.1
# content-type: application/json
Content-Type: application/x-www-form-urlencoded

{
   "username":"laotie2",
   "password":"12345"
}

